# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmMcDZLogYBXk5A7WI-hBxtbGmenucdc

# **PANDAS**

df.shape          # how big is it?
df.info()         # dtypes + null counts
df.head()         # first look
df.describe()     # statistical summary
df.isnull().sum() # null overview
df['col'].value_counts()  # distribution of key columns

"

df['col']                          # single column
df[['col1', 'col2']]               # multiple columns
df.iloc[0:5, 0:3]                  # by position
df.loc[0:4, ['col1', 'col2']]      # by label
df[df['col'] == 'value']           # filter rows
df[(condition1) & (condition2)]    # multiple conditions
df['col'].isin(['a', 'b'])         # filter by list
df.query("col == 'value'")         # SQL style
df['col'].str.contains('text')     # text filter
"""

"""
# 1. finding missing values
# 2. Droping nulls
# 3. Filling nulls
# 4. renaming columns
# 5. dropping columns and rows
# 6. changing data types
# 7. converting date columns into date type
# 8. removing Duplicates
# 9. String cleaning

df.isnull().sum()               # find nulls
df.dropna(subset=['col'])       # drop null rows
df['col'].fillna('Unknown')     # fill nulls
df.rename(columns={})           # rename columns
df.drop(columns=[])             # drop columns
df.astype()                     # fix dtypes
pd.to_datetime(df['col'])       # parse dates
df.drop_duplicates()            # remove duplicates
df['col'].str.strip().lower()   # clean strings

import pandas as pd

df = pd.read_csv('/content/netflix_titles.csv')#nrows=100,usecols=[''], parse_dates=['column with date-here[date_added]'] and many more)
df.head()

df.tail()

df['title']
type(df['title'])

type(df)
df.shape

df.columns

df.size # rows x colm

df.index

# to set index any column
(
    df
    .set_index("title")
    .head(2)
)

df.info()

df.describe() # by default - only numeric columns
df.describe(include='object') # only for non numeric columns
df.describe(include='all') # include both

(
    df.isnull()
    .sum()/len(df)*100
)

df.nunique() # each columns unique count
df['release_year'].unique() # shows unique values
df['type'].value_counts() #shows both values and their count like group by

(
    df['rating']
    .value_counts(normalize=True)  # shows % instead of count
    .mul(100)
    .round(2)
)

(
    df[['title','type','release_year']]
    .head()
)

#.iloc[] — by position (like a list)
df.iloc[1]
df.iloc[-1]

df.iloc[0:5] # index wise total 5 #last one is excluded
df.iloc[0:5, 0:5] # rows, columns  #last one is excluded

# single row by index label
df.loc[0]        # row where index = 0

# specific rows and columns by name
df.loc[0:4, ['title', 'type', 'rating']] # we need to mentioned columns and also last one in inclusive

# all rows, specific columns
df.loc[:, ['title', 'director']]

# it shows all those 3 columns where type is movie
(
    df[df['type'] == 'Movie']
    [['title', 'release_year', 'rating']]
    .head()
)

df[(df['type']=='Movie') & (df['release_year'] > 2015)] # both

df[(df['type']=='Movie') | (df['release_year'] > 2015)] #atleast one

df[~(df['type']=='Movie')] # except this condition

# instead of multiple OR conditions
# .isin() is just a shortcut to replace multiple OR conditions on the SAME column with EXACT values — nothing more, nothing less.

# these are exactly the same
df[(df['rating'] == 'PG') | (df['rating'] == 'PG-13') | (df['rating'] == 'G')]

# vs clean version
df[df['rating'].isin(['PG', 'PG-13', 'G'])]

(
    df.query("type == 'Movie' and release_year > 2015 and rating == 'PG-13'")
    [['title', 'release_year', 'country']]
    .head(10)
)

# titles that contain 'Love'
df[df['title'].str.contains('Love', na=False)] # na means null value

# country starts with 'United'
df[df['country'].str.startswith('United', na=False)]

# case insensitive search
df[df['title'].str.contains('love', case=False, na=False)]

df.isnull().sum()

# drop rows where ANY column has null
df.dropna()

# drop rows where SPECIFIC column has null
df.dropna(subset=['rating'])

# drop rows where ALL columns are null
df.dropna(how='all')

# drop columns that have nulls
df.dropna(axis=1)

# ✅ clean chaining approach
(
    df
    .dropna(subset=['director'])
    [['title', 'director', 'country']]
    .head()
)

# fill with a static value
df['rating'].fillna('Not Rated')

# text columns → fill with 'Unknown' or most frequent value
df['country'].fillna('Unknown')
df['rating'].fillna(df['rating'].mode()[0])  # most frequent rating

# fill with mean/median — for numeric columns
df['release_year'].fillna(df['release_year'].mean())

# numeric columns → fill with median (more robust than mean)
df['release_year'].fillna(df['release_year'].median())

# fill with forward fill — use previous row's value
df['date_added'].fillna(method='ffill')

# fill with backward fill — use next row's value
df['date_added'].fillna(method='bfill')

# rename specific columns
# 💼 Industry Practice — rename while chaining
(
    df.rename(columns={'listed_in': 'genre'
                       'date_added': 'added_date'
                       })
    [['title', 'genre', 'type']]
    .head()
)

# make all columns lowercase, replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')

# drop single column
df.drop(columns=['show_id'])

# drop multiple columns
df.drop(columns=['show_id', 'description'])

# drop specific rows by index
df.drop(index=[0, 1, 2])

# 💼 Industry Practice — chain it
(
    df.drop(columns=['show_id', 'description'])
    .head()
)

# check current dtypes
df.dtypes

# convert release_year from int to string
df['release_year'].astype(str)

# convert a column to category — saves memory on repetitive text
df['type'].astype('category')
df['rating'].astype('category')

df['country'].memory_usage()

df['country'].astype('category').memory_usage()

# check duplicates
df.duplicated().sum()

# check duplicates on specific column
df.duplicated(subset=['title']).sum()

# view duplicate rows
df[df.duplicated(subset=['title'])]

# drop duplicates
df.drop_duplicates()

# drop duplicates on specific column, keep last occurrence
df.drop_duplicates(subset=['title'], keep='last')

# convert date_added from string to datetime
df['date_added'] = pd.to_datetime(df['date_added'])

# now you can extract parts
df['date_added'].dt.year
df['date_added'].dt.month
df['date_added'].dt.day_name()   # Monday, Tuesday...

# 💼 Industry Practice — create new columns from dates
(
    df.assign(
        year_added = df['date_added'].dt.year,
        month_added = df['date_added'].dt.month
    )
    [['title', 'date_added', 'year_added', 'month_added']]
    .head()
)

# remove leading/trailing spaces
df['title'].str.strip()

# convert to lowercase
df['title'].str.lower()

# replace within string
df['duration'].str.replace(' min', '').str.replace(' Season', 'S')

# split a column — duration has '90 min' or '2 Seasons'
df['duration'].str.split(' ', expand=True)
#    0       1
# 0  90     min
# 1  2   Seasons